os: osx
osx_image: xcode8.1
sudo: required

language: generic

env:
  global:
    - GDAL_DRIVER_PATH=/usr/local/lib/gdalplugins
    - LDFLAGS=-L/usr/local/opt/gdal2/lib
    - CPPFLAGS=-I/usr/local/opt/gdal2/include
    - PATH=$PATH:/usr/local/opt/gdal2/bin

before_install:
  - "brew upgrade python"
  - "python3 -m venv $HOME/env"
  - "source $HOME/env/bin/activate"
  - "travis_wait 30 brew install osgeo/osgeo4mac/gdal2"

install:
  - "pip install -r requirements.txt"
  - "pip install pytest"

before_script:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 10

script:
  "py.test ."
